version: "3"
services:
  swift-server: 
    build:
      context: ./swift-server
      dockerfile: ./Dockerfile
    ports: 
      - "3000:3000"
  envoy:
    build:
      context: ./envoy
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    depends_on: 
      - swift-server